int getSingleIndex( int row,int col,int totalColumns);
void quickSort(Edge** &edges, int startingIndex, int lastIndex, int &count);
int getRandomNumber(int min, int max);
int getEdgeArraySize(int rows, int columns);
std::vector<Edge*>& setEdges(const cv::Mat &img, const std::vector<Pixel *> &pixels, std::vector<Edge*> &edges);
std::vector<Edge*>& setRGBEdges(const cv::Mat &img, const std::vector<Pixel *> &pixels, std::vector<Edge*> &edges);
bool compareEdges(const Edge* e1,const Edge* e2);
cv::Mat addColorToSegmentation(const ComponentStruct* componentStruct, int rows, int columns);
std::string getFileNameFromPath(const std::string &path);
std::vector<Pixel *>& constructImageGraph(const cv::Mat& img, std::vector<Pixel *> &pixels, int rows, int columns);
std::vector<Pixel *>& constructRGBImageGraph(const cv::Mat& img, std::vector<Pixel *> &pixels, int rows, int columns);