int getSingleIndex( int row,int col,int totalColumns);
void quickSort(Edge** &edges, int startingIndex, int lastIndex, int &count);
int getRandomNumber(int min, int max);
int getEdgeArraySize(int rows, int columns);
std::vector<Edge*>& setEdges(const cv::Mat &img, std::vector<Pixel *> &pixels, std::vector<Edge*> &edges);
std::vector<Edge*>& setRGBEdges(const cv::Mat &img, std::vector<Pixel *> &pixels, std::vector<Edge*> &edges);
bool compareEdges(Edge* e1, Edge* e2);
cv::Mat addColorToSegmentation(ComponentStruct* componentStruct, int rows, int columns);
std::string getFileNameFromPath(std::string &path);
std::vector<Pixel *>& constructImageGraph(cv::Mat& img, std::vector<Pixel *> &pixels, int rows, int columns);
std::vector<Pixel *>& constructRGBImageGraph(cv::Mat& img, std::vector<Pixel *> &pixels, int rows, int columns);